import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Contato from "@/components/Contato";
import Busca from "@/components/Busca";
import Footer from "@/components/Footer";

const global_font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={global_font.className}>
        <div className="container-global">
        <Busca />
        <Contato />
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
