export default [
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "5:50",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
    outdated: true,
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "6:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
    outdated: true,
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "6:30",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "7:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "AV. ITABUNA",
    horario: "7:15",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "7:20",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "CIDADE NOVA",
    horario: "7:20",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "AV. ITABUNA",
    horario: "7:25",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "7:30",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "CIDADE NOVA",
    horario: "7:30",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "CIDADE NOVA",
    horario: "7:40",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "VIA PRINCESA ISABEL",
    horario: "7:50",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "8:00",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "CIDADE NOVA",
    horario: "8:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "8:15",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "8:40",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "9:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "9:30",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "10:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "10:30",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "11:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "11:15",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "11:45",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "AV. ITABUNA",
    horario: "11:55",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "12:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "CIDADE NOVA",
    horario: "12:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "12:20",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "12:40",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "13:00",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "AV. ESPERANÇA",
    horario: "13:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA NORTE",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "13:15",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "VIA PRINCESA ISABEL",
    horario: "13:15",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "13:40",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "14:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "AV. ITABUNA",
    horario: "14:15",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "14:45",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "CIDADE NOVA",
    horario: "15:30",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "15:40",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "16:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "16:30",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "17:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "AV. ITABUNA",
    horario: "17:05",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "17:20",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "17:45",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "18:00",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "18:20",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "18:40",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "VIA PRINCESA ISABEL",
    horario: "18:45",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "UESC",
    via: "AV. ITABUNA",
    horario: "18:55",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "19:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "UESC",
    via: "AV. ESPERANÇA",
    horario: "19:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA NORTE",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "19:30",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "19:45",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "ATACADÃO",
    via: "AV. ITABUNA",
    horario: "19:50",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "20:00",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "20:30",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "21:00",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "21:30",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "CIDADE NOVA",
    horario: "22:00",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "TERMINAL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "22:10",
    empresa: "SM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA SUL",
  },
  {
    origem: "SALOBRINHO",
    via: "AV. ITABUNA",
    horario: "22:10",
    empresa: "VM",
    dia: "SEGUNDA - SEXTA",
    destino: "ZONA NORTE",
  },
];
